name: Testing

on:
  schedule:
    - cron: '30 6 * * 1,2,3,4,5'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday Tuesday or Wednesday
        if: github.event.schedule != '30 5 * * 1,2,3'
        run: echo "This step will be skipped on Monday, Tuesday and Wednesday"
      - name: Every time
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
      with:
        python-version: 3.8
        - name: Install dependencies
        run:
        python -m pip install --upgrade pip
                pip install -r requirements.txt
        - name: Test with pytest
              run: pytest -vv
